# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LojasKD
email: cassiomansini@gmail.com
phone: (21) 98667-8085
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude: [
  'node_modules', 
  '.gitignore',
  'gulpfile.js',
  'package.json',
  '.sass-cache',
  'bower.json',
  'bower_components'
]
